name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["🐛 bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report for Thee Cigar Maestro
        
        Thanks for taking the time to fill out this bug report! Your feedback helps us improve the application.
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🔍 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe what happened and what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Tell us how to reproduce this behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should have happened?
      placeholder: "Describe what you expected to happen..."
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: 🌐 Browser(s)
      description: What browser(s) are you experiencing this issue on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Opera
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Samsung Internet
        - Other

  - type: dropdown
    id: device
    attributes:
      label: 📱 Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other

  - type: input
    id: screen-resolution
    attributes:
      label: 🖥️ Screen Resolution
      description: What's your screen resolution? (e.g., 1920x1080)
      placeholder: "1920x1080"

  - type: dropdown
    id: feature-area
    attributes:
      label: 🎯 Feature Area
      description: Which part of the application is affected?
      options:
        - 3D Flavorverse
        - Authentication/Login
        - AI Recommendations
        - Search & Filtering
        - User Profile
        - Analytics Dashboard
        - PWA/Offline Features
        - Mobile Experience
        - Performance
        - Security
        - Other

  - type: textarea
    id: console-logs
    attributes:
      label: 🔧 Console Logs
      description: Please copy and paste any relevant console errors or logs.
      placeholder: "Paste console errors here..."
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context, screenshots, or information about the problem.
      placeholder: "Any additional information that might help..."

  - type: checkboxes
    id: environment
    attributes:
      label: 🌍 Environment
      description: Please check all that apply to your environment
      options:
        - label: I'm using the latest version
        - label: I've cleared my browser cache
        - label: I've tried in incognito/private mode
        - label: This happens consistently
        - label: This is a new issue (not previously reported)

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 🚨 Security Notice
        Please do not include any sensitive information (passwords, tokens, personal data) in this bug report.
        
        ### 📧 Follow-up
        We may reach out for additional information to help resolve this issue.
        
        **Thank you for helping us improve Thee Cigar Maestro!** 🙏